FPTJobMatch.MVC/Models/JobViewModel.cs
using Microsoft.AspNetCore.Mvc;

namespace FPTJobMatch.MVC.Models
{
    [Bind("Id, Name, CompanyName, Location, Image, Description, Requirements, JobCategoryId")]
    public class JobViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string CompanyName { get; set; } = string.Empty;
        public string Location { get; set; } = string.Empty;
        public IFormFile? Image { get; set; }
        public string Description { get; set; } = string.Empty;
        public string? Requirements { get; set; }
        public Guid JobCategoryId { get; set; }
        public string? ImagePath { get; internal set; }
        public string JobCategory { get; set; } = string.Empty;
    }
}

FPTJobMatch.MVC/Controllers/JobCategoryController.cs
using FPTJobMatch.MVC.Commons;
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Data.Entities;
using FPTJobMatch.MVC.Models;
using FPTJobMatch.MVC.Validators;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTJobMatch.MVC.Controllers
{
    public class JobCategoryController : Controller
    {
        private readonly AppDbContext _context;
        public JobCategoryController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult> Create(JobCategoryViewModel jobCategoryVM)
        {
            var statusCode = new StatusCode
            {
                Message = "Chưa thực thi",
                Code = 0,
            };
            try
            {
                var validator = new JobCategoryValidator();
                var result = validator.Validate(jobCategoryVM);
                if (result.IsValid)
                {
                    var countJobCategory = await _context.JobCategories.CountAsync();
                    var newJobCategory = new JobCategory
                    {
                        Name = jobCategoryVM.Name.Trim(),
                        Description = jobCategoryVM.Description?.Trim(),
                        Position = ++countJobCategory
                    };
                    _context.JobCategories.Add(newJobCategory);
                    await _context.SaveChangesAsync();
                    statusCode.Code = 1;
                    statusCode.Message = "Tạo thành công";
                }
            }
            catch
            {
                statusCode.Code = -1;
                statusCode.Message = "Tạo thất bại";
            }
            
            return Json(statusCode);
        }
    }
}

FPTJobMatch.MVC/Controllers/JobController.cs
using FPTJobMatch.MVC.Commons;
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Data.Entities;
using FPTJobMatch.MVC.Models;
using FPTJobMatch.MVC.Validators;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FPTJobMatch.MVC.Controllers
{
    public class JobController : Controller
    {
        private readonly AppDbContext _context;
        public JobController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.JobCategories = await GetJobCategorySelectList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobViewModel jobVM)
        {
            var validator = new JobValidator();
            try
            {
                var result = await validator.ValidateAsync(jobVM);
                if (result.IsValid)
                {
                    var countJob = await _context.Jobs.CountAsync();
                    var newJob = new Job
                    {
                        Name = jobVM.Name.Trim(),
                        Description = jobVM.Description.Trim(),
                        Requirements = jobVM.Requirements?.Trim(),
                        JobCategoryId = jobVM.JobCategoryId,
                        ImagePath = jobVM.ImagePath,
                        CompanyName = jobVM.CompanyName,
                        Location = jobVM.Location,
                        Position = countJob + 1,
                    };
                    _context.Jobs.Add(newJob);
                    await _context.SaveChangesAsync();
                    //ViewBag.Announcement = "Tạo thành công";
                    ViewData[ViewBags.ANNOUNCEMENT] = "Tạo thành công";
                    return RedirectToAction("Create");
                }
            }
            catch
            {
                ViewBag.JobCategories = await GetJobCategorySelectList();

                //ViewBag.Announcement = "Tạo thất bại";
                ViewData[ViewBags.ANNOUNCEMENT] = "Tạo thất bại";
            }

            return View(jobVM);
        }

        public async Task<IActionResult> Edit(Guid idJob)
        {
            var jobVM = await _context.Jobs
                .Where(j => j.Id.Equals(idJob))
                .Select(j => new JobViewModel
                {
                    Id = j.Id,
                    Name = j.Name,
                    Description = j.Description,
                    Requirements = j.Requirements,
                    JobCategoryId = j.JobCategoryId,
                })
                .SingleOrDefaultAsync();

            ViewBag.JobCategories = await GetJobCategorySelectList();

            return View(nameof(Create), jobVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(JobViewModel jobVM)
        {
            var validator = new JobValidator();
            try
            {
                var result = await validator.ValidateAsync(jobVM);
                if (result.IsValid)
                {
                    var job = await _context.Jobs
                        .Where(j => j.Id.Equals(jobVM.Id))
                        .SingleOrDefaultAsync();

                    if (job != null)
                    {
                        job.Name = jobVM.Name.Trim();
                        job.Description = jobVM.Description.Trim();
                        job.Requirements = jobVM.Requirements?.Trim();
                        job.JobCategoryId = jobVM.JobCategoryId;

                        await _context.SaveChangesAsync();
                        //ViewBag.Announcement = "Tạo thành công";
                        ViewData[ViewBags.ANNOUNCEMENT] = "Tạo thành công";
                        return RedirectToAction("Create");
                    }
                }
            }
            catch
            {
                ViewBag.JobCategories = await GetJobCategorySelectList();

                //ViewBag.Announcement = "Tạo thất bại";
                ViewData[ViewBags.ANNOUNCEMENT] = "Tạo thất bại";
            }

            return View(nameof(Create), jobVM);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid idJob)
        {
            var statusCode = false;
            var message = "Chưa thực thi";
            try
            {
                var job = await _context.Jobs
                        .Where(j => j.Id.Equals(idJob))
                        .SingleOrDefaultAsync();

                if (job != null)
                {
                    _context.Jobs.Remove(job);

                    await _context.SaveChangesAsync();
                    statusCode = true;
                    message = "Xóa thành công";
                }
            }
            catch
            {
                message = "Lỗi thực thi";
            }

            return Json(new { message, statusCode });
        }

        public IActionResult GetAll()
        {
            return ViewComponent("JobList");
        }

        private async Task<SelectList> GetJobCategorySelectList()
        {
            var listJob = await _context.JobCategories
                .OrderBy(jt => jt.Position)
                .Select(jt => new Item
                {
                    Id = jt.Id,
                    Name = jt.Name,
                })
                .ToListAsync();
            listJob.Insert(0, new Item
            {
                Id = Guid.Empty,
                Name = "=== Chọn Job Category ==="
            });
            var selectList = new SelectList(listJob, "Id", "Name");
            return selectList;
        }
    }
}

FPTJobMatch.MVC/ViewComponents/JobListViewComponent.cs
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTJobMatch.MVC.ViewComponents
{
    public class JobListViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public JobListViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(bool isForHome = false)
        {
            var items = await _context!.Jobs!
                //.Where()
                .Include(j => j.JobCategory)
                .Select(j => new JobViewModel
                {
                    Id = j.Id,
                    Name = j.Name,
                    CompanyName = j.CompanyName,
                    Location = j.Location,
                    Description = j.Description,
                    ImagePath = j.ImagePath,
                    JobCategory = j.JobCategory.Name,
                    Requirements = j.Requirements
                })
                .ToListAsync();
            if (isForHome)
            {
                return View("HomeViewJobList", items);
            }
            return View(items);
        }
        private Task<List<JobViewModel>> GetItemsAsync()
        {
            return _context!.Jobs!
                //.Where()
                .Select(j => new JobViewModel
                {
                    Id = j.Id,
                    Name = j.Name,
                    CompanyName = j.CompanyName,
                    Location = j.Location,
                    Description = j.Description,
                    ImagePath = j.ImagePath,
                    JobCategory = j.JobCategory.Name,
                    Requirements = j.Requirements
                })
                .ToListAsync();
        }
    }
}

FPTJobMatch.MVC/Views/Job/Create.cshtml
@using FPTJobMatch.MVC.Commons
@model FPTJobMatch.MVC.Models.JobViewModel

@{
    ViewData["Title"] = "Create";
    var isCreate = Model == null || Model.Id == Guid.Empty;
    string buttonName = isCreate ? "Create" : "Update";
    string actionName = isCreate ? "Create" : "Edit";
}

<h1>Create a job</h1>
<button type="button" onclick="openModalCreateJobCategory();">Create a job Category</button>
<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="@actionName" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" class="form-control" />

            <div id="announcement">@ViewData[ViewBags.ANNOUNCEMENT]</div>

            <div class="form-group">
                <label asp-for="Name" class="control-label">Job Title</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CompanyName" class="control-label">Company Name</label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Location" class="control-label">Location</label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Image" class="control-label">Job Image</label>
                <input asp-for="Image" type="file" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Requirements" class="control-label">Requirements</label>
                <textarea asp-for="Requirements" class="form-control"></textarea>
                <span asp-validation-for="Requirements" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="JobCategoryId" class="control-label">Job Category</label>
                <select asp-for="JobCategoryId" asp-items="ViewBag.JobCategories" class="form-control"></select>
                <span asp-validation-for="JobCategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="@buttonName" class="btn btn-primary" />
            </div>
        </form>
    </div>

    <div id="divJobList" class="col-md-8">
        @await Component.InvokeAsync("JobList")
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
          // let buttonOpenModal = document.getElementById("buttonOpenModal");
          // const modalSizes = {
          //     small: "modal-sm",
          //     medium: "",
          //     large: "modal-lg",
          //     extraLarge: "modal-xl",
          // }
        document.addEventListener("DOMContentLoaded", () => {
            // openModal("Title", "Test thử nghiệm");
            // openModal("Title", "Test thử nghiệm", modalSizes.extraLarge);
        });


        function openModalCreateJobCategory(){
            $.ajax({
                type: "GET",
                url: '@Url.Action("Create", "JobCategory")',
                // cache: false,
                // dataType: "json",
                // data: {},
                complete: function () {

                },
                success: function (data, textStatus, XMLHttpRequest) {
                    openModal("Job Category", data, modalSizes.large);
                },
                error: function (error) {
                    // ???
                },
            });
        }
        function createJobCategory(){
            let formJobCategory = document.getElementById("formJobCategory");
            let jobCategoryData;
            if(formJobCategory) {
                let inputId = formJobCategory.querySelector("input[Id='Id']");
                let inputName = formJobCategory.querySelector("input[Id='Name']");
                let textareaDescription = formJobCategory.querySelector("textarea[Id='Description']");
                jobCategoryData = {
                    id: inputId.value,
                    name: inputName.value,
                    description: textareaDescription.value
                }
            }
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "JobCategory")',
                data: {jobCategoryVM: jobCategoryData},
                complete: function () {
                    //=== Đóng Modal lại ===//
                    closeModal();
                    //TODO:=== Refresh danh sách Job Type===//
                },
                success: function (response) {
                  console.log("Response: ", response.message);
                },
                error: function (error) {
                    // ???
                },
            });
        }
        function deleteJob(idJob){
            $.ajax({
                type: "POST",
                url: '@Url.Action("Delete", "Job")',
                data: { idJob },
                complete: function () {
                    //TODO:=== Refresh danh sách Job ===//
                    reloadJobList();
                },
                success: function (response) {
                  console.log("Response: ", response.message);
                  console.log("StatusCode: ", response.statusCode);
                },
                error: function (error) {
                    // ???
                },
            });
        }

        function reloadJobList(){
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetAll", "Job")',
                // data: { idJob: idJob},
                complete: function () {

                },
                success: function (response) {
                  let divJobList = document.getElementById("divJobList");
                  if(divJobList){
                      divJobList.innerHTML = response;
                  }
                },
                error: function (error) {
                    // ???
                },
            });
        }
    </script>
}