FPTJobMatch.MVC/Models/JobSeekerViewModel.cs
using FPTJobMatch.MVC.Enums;
using Microsoft.AspNetCore.Mvc;

namespace FPTJobMatch.MVC.Models
{
    [Bind("Id, FullName, DateOfBirth, Gender, Occupation, Email, Phone")]
    public class JobSeekerViewModel
    {
        public Guid Id { get; set; }
        public string FullName { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public DateOnly DateOfBirth { get; set; }
        public GenderEnum Gender { get; set; }
        public string Email { get; set; } = string.Empty;
        public string Phone { get; set; } = string.Empty;

        public int Position { get; set; }

        public OccupationEnum Occupation { get; set; }
    }
}

FPTJobMatch.MVC/Controllers/JobSeekerController.cs
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Data.Entities;
using FPTJobMatch.MVC.Helpers;
using FPTJobMatch.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTJobMatch.MVC.Controllers
{
    public class JobSeekerController : Controller
    {
        private readonly AppDbContext _context;
        public JobSeekerController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(JobSeekerViewModel jobSeeker)
        {
            try
            {
                var countJobSeeker = await _context.JobSeekers.CountAsync();
                var newJobSeeker = new JobSeeker
                {
                    Position = ++countJobSeeker,

                };

                newJobSeeker.GetNameFromFullname(jobSeeker.FullName);
                _context.JobSeekers.Add(newJobSeeker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            catch
            {
            }
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            return View(jobSeeker);
        }

        public async Task<IActionResult> Edit(Guid idJobSeeker)
        {
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            
            var jobSeekerVM = await _context.JobSeekers
                .Where(j => j.Id.Equals(idJobSeeker))
                .Select(j => new JobSeekerViewModel
                {
                    Id = j.Id,
                    FullName = j.FullName,
                    Name = j.Name,
                    Position = j.Position,
                    Phone = j.Phone,    
                    Email = j.Email,
                    Occupation = j.Occupation,
                    Gender = j.Gender,
                    DateOfBirth = j.DateOfBirth,
                })
                .SingleOrDefaultAsync();
           
            return View(nameof(Create), jobSeekerVM);
        }
        [HttpPost]
        
        public async Task<IActionResult> Edit(JobSeekerViewModel jobSeekerVM)
        {
            try
            {
                var jobSeeker = await _context.JobSeekers
                    .FindAsync(jobSeekerVM.Id);
                jobSeeker.FullName = jobSeekerVM.FullName;
                jobSeeker.GetNameFromFullname(jobSeekerVM.FullName);
                jobSeeker.DateOfBirth = jobSeekerVM.DateOfBirth;
                jobSeeker.Gender = jobSeekerVM.Gender;
                jobSeeker.Occupation = jobSeekerVM.Occupation;
                jobSeeker.Email = jobSeekerVM.Email;
                jobSeeker.Phone = jobSeekerVM.Phone;

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            catch
            {
            }
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            return View(nameof(Create), jobSeekerVM);
        }
    }
}

FPTJobMatch.MVC/ViewComponents/JobSeekerListViewComponent.cs
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTJobMatch.MVC.ViewComponents
{
    public class JobSeekerListViewComponent: ViewComponent
    {
        private readonly AppDbContext _context;
        public JobSeekerListViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var jobSeekers = await _context.JobSeekers
                .OrderBy(c => c.Position)
                .Select(c => new JobSeekerViewModel
                {
                    Id = c.Id,
                    FullName = c.FullName,
                    Name = c.Name,
                    Position = c.Position,
                    Phone = c.Phone,
                    Email = c.Email,
                    Occupation = c.Occupation,
                    Gender = c.Gender,
                    DateOfBirth = c.DateOfBirth,
                })
                .ToListAsync();
            return View(jobSeekers);
        }
    }
}

FPTJobMatch.MVC/Views/JobSeeker/Create.cshtml
@model FPTJobMatch.MVC.Models.JobSeekerViewModel
@using FPTJobMatch.MVC.Enums

@{
    ViewData["Title"] = "Create";
    bool isCreate = Model == null;
    string buttonName = isCreate ? "Create" : "Update";
    string actionName = isCreate ? "Create" : "Edit";
}

<h1>Create JobSeeker</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="@actionName">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" type="hidden" class="form-control" />
                <input asp-for="Name" type="hidden" class="form-control" />

            
            <div class="form-group">
                <label asp-for="FullName" class="control-label">Name</label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>

            <div class="form-group" style="display: flex; justify-content: space-around;">
                @foreach (var item in Enum.GetValues(typeof(GenderEnum)))
                {
                    string checkedStatus = (!isCreate && (GenderEnum)item == Model.Gender)
                    ? "checked" : "";
                        <label class="control-label">
                            <input name="Gender" type="radio" value="@((GenderEnum)item)" @checkedStatus />
                        @item.ToString()
                        </label>
                }
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Date of Birth</label>
                <input asp-for="DateOfBirth" type="date" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Occupation" class="control-label"></label>
                <select asp-for="Occupation" asp-items="ViewBag.Occupations" class="form-control"></select>
                <span asp-validation-for="Occupation" class="text-danger"></span>
            </div>
            <div class="form-group" style="text-align: center">
                <input type="submit" value="@buttonName" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-8">
        @await Component.InvokeAsync("JobSeekerList")
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}