FPTJobMatch.MVC/Controllers/CompanyController.cs
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Data.Entities;
using FPTJobMatch.MVC.Helpers;
using FPTJobMatch.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTJobMatch.MVC.Controllers
{
    public class CompanyController : Controller
    {
        private readonly AppDbContext _context;

        public CompanyController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CompanyViewModel companyVM)
        {
            try
            {
                var countCompany = await _context.Companies.CountAsync();
                var newCompany = new Company
                {
                    Name = companyVM.Name,
                    Address = companyVM.Address,
                    Email = companyVM.Email,
                    Hotline = companyVM.Hotline,
                    TaxNumber = companyVM.TaxNumber,
                    Position = countCompany + 1,
                };
                _context.Companies.Add(newCompany);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            catch
            {

            }
            
            return View(companyVM);
        }

        public async Task<IActionResult> Edit(Guid idCompany)
        {
            var companyVM = await _context.Companies
                .Where(c => c.Id.Equals(idCompany))
                .Select(c => new CompanyViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    Position = c.Position,
                    Hotline = c.Hotline,
                    Email = c.Email,
                    TaxNumber= c.TaxNumber,
                    Address = c.Address,
                    
                })
                .SingleOrDefaultAsync();
            return View(nameof(Create), companyVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CompanyViewModel companyVM)
        {
            try
            {
                var company = await _context.Companies
                    .FindAsync(companyVM.Id);
                if (company != null)
                {
                    company.Name = companyVM.Name;
                    company.TaxNumber = companyVM.TaxNumber;
                    company.Address = companyVM.Address;
                    company.Email = companyVM.Email;
                    company.Hotline = companyVM.Hotline;

                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Create));
                }
            }
            catch
            {
            }
            return View(nameof(Create), companyVM);
        }
    }
}

FPTJobMatch.MVC/Controllers/JobController.cs
using FPTJobMatch.MVC.Commons;
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Data.Entities;
using FPTJobMatch.MVC.Models;
using FPTJobMatch.MVC.Validators;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FPTJobMatch.MVC.Controllers
{
    public class JobController : Controller
    {
        private readonly AppDbContext _context;
        public JobController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.JobCategories = await GetJobCategorySelectList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobViewModel jobVM)
        {
            var validator = new JobValidator();
            try
            {
                var result = await validator.ValidateAsync(jobVM);
                if (result.IsValid)
                {
                    var countJob = await _context.Jobs.CountAsync();
                    var newJob = new Job
                    {
                        Name = jobVM.Name.Trim(),
                        Description = jobVM.Description.Trim(),
                        Requirements = jobVM.Requirements?.Trim(),
                        JobCategoryId = jobVM.JobCategoryId,
                        ImagePath = jobVM.ImagePath,
                        CompanyName = jobVM.CompanyName,
                        Location = jobVM.Location,
                        Position = countJob + 1,
                    };
                    _context.Jobs.Add(newJob);
                    await _context.SaveChangesAsync();
                    //ViewBag.Announcement = "Tạo thành công";
                    ViewData[ViewBags.ANNOUNCEMENT] = "Tạo thành công";
                    return RedirectToAction("Create");
                }
            }
            catch
            {
                ViewBag.JobCategories = await GetJobCategorySelectList();

                //ViewBag.Announcement = "Tạo thất bại";
                ViewData[ViewBags.ANNOUNCEMENT] = "Tạo thất bại";
            }

            return View(jobVM);
        }

        public async Task<IActionResult> Edit(Guid idJob)
        {
            var jobVM = await _context.Jobs
                .Where(j => j.Id.Equals(idJob))
                .Select(j => new JobViewModel
                {
                    Id = j.Id,
                    Name = j.Name,
                    Description = j.Description,
                    Requirements = j.Requirements,
                    JobCategoryId = j.JobCategoryId,
                })
                .SingleOrDefaultAsync();

            ViewBag.JobCategories = await GetJobCategorySelectList();

            return View(nameof(Create), jobVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(JobViewModel jobVM)
        {
            var validator = new JobValidator();
            try
            {
                var result = await validator.ValidateAsync(jobVM);
                if (result.IsValid)
                {
                    var job = await _context.Jobs
                        .Where(j => j.Id.Equals(jobVM.Id))
                        .SingleOrDefaultAsync();

                    if (job != null)
                    {
                        job.Name = jobVM.Name.Trim();
                        job.Description = jobVM.Description.Trim();
                        job.Requirements = jobVM.Requirements?.Trim();
                        job.JobCategoryId = jobVM.JobCategoryId;

                        await _context.SaveChangesAsync();
                        //ViewBag.Announcement = "Tạo thành công";
                        ViewData[ViewBags.ANNOUNCEMENT] = "Tạo thành công";
                        return RedirectToAction("Create");
                    }
                }
            }
            catch
            {
                ViewBag.JobCategories = await GetJobCategorySelectList();

                //ViewBag.Announcement = "Tạo thất bại";
                ViewData[ViewBags.ANNOUNCEMENT] = "Tạo thất bại";
            }

            return View(nameof(Create), jobVM);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid idJob)
        {
            var statusCode = false;
            var message = "Chưa thực thi";
            try
            {
                var job = await _context.Jobs
                        .Where(j => j.Id.Equals(idJob))
                        .SingleOrDefaultAsync();

                if (job != null)
                {
                    _context.Jobs.Remove(job);

                    await _context.SaveChangesAsync();
                    statusCode = true;
                    message = "Xóa thành công";
                }
            }
            catch
            {
                message = "Lỗi thực thi";
            }

            return Json(new { message, statusCode });
        }

        public IActionResult GetAll()
        {
            return ViewComponent("JobList");
        }

        private async Task<SelectList> GetJobCategorySelectList()
        {
            var listJob = await _context.JobCategories
                .OrderBy(jt => jt.Position)
                .Select(jt => new Item
                {
                    Id = jt.Id,
                    Name = jt.Name,
                })
                .ToListAsync();
            listJob.Insert(0, new Item
            {
                Id = Guid.Empty,
                Name = "=== Chọn Job Category ==="
            });
            var selectList = new SelectList(listJob, "Id", "Name");
            return selectList;
        }
    }
}

FPTJobMatch.MVC/Controllers/JobSeekerController.cs
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Data.Entities;
using FPTJobMatch.MVC.Helpers;
using FPTJobMatch.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTJobMatch.MVC.Controllers
{
    public class JobSeekerController : Controller
    {
        private readonly AppDbContext _context;
        public JobSeekerController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(JobSeekerViewModel jobSeeker)
        {
            try
            {
                var countJobSeeker = await _context.JobSeekers.CountAsync();
                var newJobSeeker = new JobSeeker
                {
                    Position = ++countJobSeeker,

                };

                newJobSeeker.GetNameFromFullname(jobSeeker.FullName);
                _context.JobSeekers.Add(newJobSeeker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            catch
            {
            }
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            return View(jobSeeker);
        }

        public async Task<IActionResult> Edit(Guid idJobSeeker)
        {
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            
            var jobSeekerVM = await _context.JobSeekers
                .Where(j => j.Id.Equals(idJobSeeker))
                .Select(j => new JobSeekerViewModel
                {
                    Id = j.Id,
                    FullName = j.FullName,
                    Name = j.Name,
                    Position = j.Position,
                    Phone = j.Phone,    
                    Email = j.Email,
                    Occupation = j.Occupation,
                    Gender = j.Gender,
                    DateOfBirth = j.DateOfBirth,
                })
                .SingleOrDefaultAsync();
           
            return View(nameof(Create), jobSeekerVM);
        }
        [HttpPost]
        
        public async Task<IActionResult> Edit(JobSeekerViewModel jobSeekerVM)
        {
            try
            {
                var jobSeeker = await _context.JobSeekers
                    .FindAsync(jobSeekerVM.Id);
                jobSeeker.FullName = jobSeekerVM.FullName;
                jobSeeker.GetNameFromFullname(jobSeekerVM.FullName);
                jobSeeker.DateOfBirth = jobSeekerVM.DateOfBirth;
                jobSeeker.Gender = jobSeekerVM.Gender;
                jobSeeker.Occupation = jobSeekerVM.Occupation;
                jobSeeker.Email = jobSeekerVM.Email;
                jobSeeker.Phone = jobSeekerVM.Phone;

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            catch
            {
            }
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            return View(nameof(Create), jobSeekerVM);
        }
    }
}

FPTJobMatch.MVC/Controllers/UserController.cs
using FPTJobMatch.MVC.Data;
using FPTJobMatch.MVC.Enums;
using FPTJobMatch.MVC.Helpers;
using FPTJobMatch.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration.UserSecrets;
using Mono.TextTemplating;
using System;

namespace FPTJobMatch.MVC.Controllers
{
    public class UserController : Controller
    {
        //private readonly DataService _serviceData;
        private readonly AppDbContext _context;
        public UserController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            ViewBag.Occupations = DataHelper.GetOccupationSelectList();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            if (user == null) return BadRequest();
            try
            {
                if (!string.IsNullOrEmpty(user.FullName))
                {
                    //var listUser = _serviceData.GetUsers();
                    //listUser.Add(user);
                    user.FullName = user.FullName.Trim();
                    user.Name = user.GetNameFromFullname(user.FullName);

                    var count = await _context.Users.CountAsync();
                    user.Position = ++count;

                    await _context.Users.AddAsync(user);

                    await _context.SaveChangesAsync();

                    return RedirectToAction("Create");
                }

                //=== Trả dữ liệu User về lại View cho người dùng xem lại ===//
                ViewBag.Occupations = DataHelper.GetOccupationSelectList();
                //return View("Create", user);
            }
            catch { }

            return View(user);
        }

        public async Task<IActionResult> Edit(Guid idUser)
        {
            //var listUser = _serviceData.GetUsers();
            //var user = listUser
            //    .Where(u => u.Id == idUser)
            //    .SingleOrDefault();
            var user = await _context.Users
                .Where(u => u.Id == idUser)
            .SingleOrDefaultAsync();

            ViewBag.Occupations = DataHelper.GetOccupationSelectList();

            return View(nameof(Create), user);
        }

        [HttpPost]
        public IActionResult Edit(User user)
        {
            if (user != null && !string.IsNullOrEmpty(user.FullName))
            {
                //var listUser = _serviceData.GetUsers();
                //var userInList = listUser
                //    .Where(u => u.Id == user.Id)
                //    .SingleOrDefault();
                var userInList = _context.Users
                   .Where(u => u.Id == user.Id)
                   .SingleOrDefault();
                if (userInList != null)
                {
                    userInList.FullName = user.FullName;
                    userInList.Phone = user.Phone;
                    userInList.Email = user.Email;
                    userInList.Gender = user.Gender;
                    userInList.DateOfBirth = user.DateOfBirth;
                    userInList.Occupation = user.Occupation;

                    return RedirectToAction(nameof(Create));
                }
                else
                {
                    return BadRequest();
                }
            }

            ViewBag.Occupations = DataHelper.GetOccupationSelectList();
            return View(nameof(Create), user);
        }

        //private SelectList GetOccupationSelectList()
        //{
        //    var occupations = from OccupationEnum job in Enum.GetValues(typeof(OccupationEnum))
        //                      select new
        //                      {
        //                          Id = job,
        //                          Name = job.ToString()
        //                      };
        //    return new SelectList(occupations, "Id", "Name", 4);
        //}
    }
}

FPTJobMatch.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FPTJobMatch.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FPTJobMatch.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_NavigationPartialView" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark text-white border-top footer">
        <div class="container">
            &copy; 2024 - FPTJobMatch.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <button id="buttonOpenModal" type="button" hidden class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myAppModal">
        Launch modal
    </button>
    <!-- Modal -->
    <div class="modal fade" id="myAppModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div id="divModalDialog" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title fs-5" id="divModalTitle">Modal title</div>
                    <button id="btnCloseModal" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="divModalBody" class="modal-body">
                    @* Đây là nội dung chính của Modal *@
                </div>
                <div id="divModalError" class="modal-error-message">
                    @* Đây là thông báo lỗi trên Form *@
                </div>
                @* <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div> *@
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FPTJobMatch.MVC/Views/Shared/_NavigationPartialView.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FPTJobMatch.MVC</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="JobSeeker" asp-action="Create">JobSeeker</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Create">Company</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="Create">Job</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">User</a>
                </li>
            </ul>
        </div>
    </div>
</nav>